{% set name = "dotnet-monitor" %}
{% set version = "9.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dotnet/dotnet-monitor/archive/v{{ version }}.tar.gz
  sha256: 057fef4200d58e05e29c6f4ee0859697b891da32413f98300bfb704fc8a97ee8

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

test:
  commands:
    - dotnet-monitor --help

about:
  home: https://github.com/dotnet/dotnet-monitor
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: A tool that allows you to gather diagnostic data from running applications using HTTP endpoints
  dev_url: https://github.com/dotnet/dotnet-monitor

extra:
  recipe-maintainers:
    - danielnachun
