context:
  version: "10.0.4"

package:
  name: dotnet-monitor
  version: ${{ version }}

source:
  url: https://github.com/dotnet/dotnet-monitor/archive/v${{ version }}.tar.gz
  sha256: cc4e8c9edba7784c8b53fd4128c1bdf72d11545e6686bc9a6566117d7a77a8b3

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-monitor --help

about:
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: A tool that allows you to gather diagnostic data from running applications using HTTP endpoints
  homepage: https://github.com/dotnet/dotnet-monitor
  repository: https://github.com/dotnet/dotnet-monitor

extra:
  recipe-maintainers:
    - danielnachun
