context:
  version: "10.0.3"

package:
  name: dotnet-monitor
  version: ${{ version }}

source:
  url: https://github.com/dotnet/dotnet-monitor/archive/v${{ version }}.tar.gz
  sha256: 9b5f68445d0d17fcb275395e975977dfaef1b32ea89eebb2ff8f684ab9287ae6

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-monitor --help

about:
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: A tool that allows you to gather diagnostic data from running applications using HTTP endpoints
  homepage: https://github.com/dotnet/dotnet-monitor
  repository: https://github.com/dotnet/dotnet-monitor

extra:
  recipe-maintainers:
    - danielnachun
