context:
  version: "9.0.1"

package:
  name: dotnet-monitor
  version: ${{ version }}

source:
  url: https://github.com/dotnet/dotnet-monitor/archive/v${{ version }}.tar.gz
  sha256: c6878ff59a886bdd63dced357a16c1d0ec7b5771bacb4bd89fcb6e3d9a13c578

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-monitor --help

about:
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: A tool that allows you to gather diagnostic data from running applications using HTTP endpoints
  homepage: https://github.com/dotnet/dotnet-monitor
  repository: https://github.com/dotnet/dotnet-monitor

extra:
  recipe-maintainers:
    - danielnachun
