context:
  version: "9.0.3"

package:
  name: dotnet-monitor
  version: ${{ version }}

source:
  url: https://github.com/dotnet/dotnet-monitor/archive/v${{ version }}.tar.gz
  sha256: 5e5462c857dfb69fea7c8bde1c72a03a325282c8899056eccc13cedc32695005

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-monitor --help

about:
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: A tool that allows you to gather diagnostic data from running applications using HTTP endpoints
  homepage: https://github.com/dotnet/dotnet-monitor
  repository: https://github.com/dotnet/dotnet-monitor

extra:
  recipe-maintainers:
    - danielnachun
