context:
  version: "9.0.2"

package:
  name: dotnet-monitor
  version: ${{ version }}

source:
  url: https://github.com/dotnet/dotnet-monitor/archive/v${{ version }}.tar.gz
  sha256: a05ff4eb6960afcbc69525f98ee979c47de3e3859cbe252f345a1db3765c1158

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - jq
    - nuget-license
  run:
    - dotnet

tests:
  - script:
      - dotnet-monitor --help

about:
  license: MIT
  license_file:
    - LICENSE.TXT
    - license-files/
  summary: A tool that allows you to gather diagnostic data from running applications using HTTP endpoints
  homepage: https://github.com/dotnet/dotnet-monitor
  repository: https://github.com/dotnet/dotnet-monitor

extra:
  recipe-maintainers:
    - danielnachun
